language: python
services:
  - docker
env:
  - IMAGE_COMMIT_NAME=x007007007/easy-climb-wall:${TRAVIS_COMMIT}
  - IMAGE_LATEST_NAME=x007007007/easy-climb-wall:latest
  - IMAGE_TAG_NAME=x007007007/easy-climb-wall:${TRAVIS_TAG}
  - VERSION=${TRAVIS_TAG#v}
  - IMAGE_COMMIT_NAME=x007007007/easy-climb-wall:latest

before_install:
  - echo "`date` - travis CI build"
  - echo ${IMAGE_COMMIT_NAME}

install:
  - docker build --build-arg=VERSION=${VERSION} -t ${IMAGE_COMMIT_NAME} .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script:
      - docker tag ${IMAGE_COMMIT_NAME} {$IMAGE_TAG_LATEST}
      - docker push {$IMAGE_TAG_NAME}
    on:
      branch: master
  - provider: script
    script:
      - docker tag ${IMAGE_COMMIT_NAME} {$IMAGE_TAG_NAME}
      - docker push {$IMAGE_TAG_NAME}
    on:
      tags: true