version: "3.8"

networks:
  traefik-public:
    external: true

services:
  climb-wall:
    image:  x007007007/easy-climb-wall
    networks:
      - traefik-public
    environment:
      DOCKER_SERVICE_NAME: 'proxy-climb-wall'
      SECRET_KEY: ${SECRET_KEY:-set a secret key}
    volumes:
      - climb-wall-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.labels.proxy-climb_wall==true
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.routers.climb_wall-https.rule=Host(`climb-wall.${DOMAIN?Variable not set}`)
        - traefik.http.routers.climb_wall-https.entrypoints=https
        - traefik.http.routers.climb_wall-https.tls.certresolver=le
        - traefik.http.routers.climb_wall-https.tls=true
        - traefik.http.routers.climb_wall-https.service=climb_wall
        - traefik.http.services.climb_wall.loadbalancer.server.port=8000

volumes:
  climb-wall-data:
    name: 'proxy-climb-wall-data'
