# Generated by Django 4.0.4 on 2022-05-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_pipeline.templatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableNextStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_available_next_status_map_set', to='common_pipeline.statusmodel')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_available_next_status_map_set', to='common_pipeline.statusmodel')),
            ],
        ),
    ]
