# Generated by Django 4.0.4 on 2022-05-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_pipeline', '0002_statusmodel_next_status_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
