# Generated by Django 4.0.4 on 2022-05-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_action', '0001_initial'),
        ('common_pipeline', '0003_statusmodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='is_finish_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='is_record_status_change_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='start_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_pipeline.statusmodel'),
        ),
        migrations.CreateModel(
            name='ProcessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_pipeline.statusmodel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_pipeline.processmodel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_pipeline.templatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeStatusActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_action.refermodel')),
                ('change_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_pipeline.availablenextstatusmodel')),
            ],
        ),
    ]
