# Generated by Django 4.0.4 on 2022-05-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_pipeline', '0004_statusmodel_is_finish_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeStatusStrategyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('change_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_pipeline.availablenextstatusmodel')),
                ('sub_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_pipeline.templatemodel')),
            ],
        ),
    ]
