# Generated by Django 4.0.4 on 2022-05-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_pipeline', '0006_changestatusactionmodel_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_pipeline.processmodel'),
        ),
    ]
