# Generated by Django 4.0.4 on 2022-05-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMethodRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('postfix_url', models.CharField(max_length=254)),
                ('allow_method', models.ManyToManyField(through='common_callback_proxy.ConfigMethodRel', to='common_code.httpmethod')),
            ],
        ),
        migrations.AddField(
            model_name='configmethodrel',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_callback_proxy.configmodel'),
        ),
        migrations.AddField(
            model_name='configmethodrel',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_code.httpmethod'),
        ),
        migrations.AlterUniqueTogether(
            name='configmethodrel',
            unique_together={('config', 'method')},
        ),
    ]
