# Generated by Django 4.0.4 on 2022-05-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_action', '0003_refermodel_action_retry_and_more'),
        ('common_callback_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmodel',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_action.refermodel'),
        ),
    ]
