# Generated by Django 4.0.4 on 2022-05-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_callback_proxy', '0003_historymodel_configapischemaitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configmodel',
            old_name='allow_method',
            new_name='allow_method_set',
        ),
    ]
