# Generated by Django 4.0.4 on 2022-05-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('path', models.CharField(max_length=254)),
                ('host', models.CharField(max_length=254)),
                ('enabled', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=254)),
                ('encryption', models.CharField(max_length=64)),
                ('timeout', models.PositiveIntegerField(default=20)),
                ('pid', models.IntegerField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
