# Generated by Django 4.0.4 on 2022-05-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('HEAD', 'HEAD'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('PUT', 'PUT'), ('OPTIONAL', 'OPTIONAL')], max_length=16)),
            ],
        ),
    ]
