# Generated by Django 4.0.4 on 2022-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_action', '0002_alter_refermodel_config_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='refermodel',
            name='action_retry',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='refermodel',
            name='action_retry_interval',
            field=models.IntegerField(default=60),
        ),
    ]
