# Generated by Django 4.0.4 on 2022-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_action', '0003_refermodel_action_retry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerycfgmodel',
            name='eta_delta_second',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celerycfgmodel',
            name='expires',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
